#!/usr/bin/env python3
"""
Create yet another little script.

Usage: {script} [options] NAME

Arguments:
    NAME - Filename of the script to be created.

Options:
    -h, --help
        Show this screen and exit.

    --verbose
        Raise verbosity level.
"""
import sys
from os import environ, system
from contextlib import suppress
from pathlib import Path


def main(script_name: str, *script_args: str):
    doc = __doc__.format(script=Path(script_name).name)
    args = __import__("docopt").docopt(doc, script_args)
    setattr(debug, "enabled", args["--verbose"])
    debug(f"Running with arguments {dict(args)!r}")
    projects = Path(environ["GIT_PROJECTS_DIR"] or "~/Documents/Projects")
    name = "-".join(args["NAME"].split()).lower()
    debug(f"script-name: {name}")
    path = projects.joinpath("small_scripts").joinpath(name)
    if path.exists():
        print("ERROR: Script with this name already exists!", file=sys.stderr)
        exit(1)
    debug(f"script-path: {path}")
    script = Path(__file__).parent.joinpath("script-template").read_text()
    path.write_text(script.replace("Aboba about aboba.", args["NAME"]))
    # TODO: fix filename manhandling
    system(f"$EDITOR '{path}'")
    system("$SHELL")


def debug(msg: str):
    if getattr(debug, "enabled", False):
        print(msg)


if __name__ == "__main__":
    with suppress(KeyboardInterrupt):
        main(*sys.argv)
