#!/bin/python3

from sys import stdin, argv
from string import ascii_letters, digits, punctuation
from hashlib import sha3_512 as shasum
from pathlib import Path

MASTER_PASSWORD = (Path(__file__).resolve().parent / "KEY").read_text().strip()
allowed_characters = list(sorted(set(digits + ascii_letters + "@.")))


def get_password(entropy):
    num = int(shasum((entropy + MASTER_PASSWORD).encode()).hexdigest(), 16)
    result = []
    while num:
        num, i = divmod(num, len(allowed_characters))
        result.append(allowed_characters[i])
    return "".join(result)


assert len(argv) > 1
password = get_password("".join(argv[1]))
if len(argv) > 2:
    password = password[: int(argv[2])]
print(password)
