#!/bin/python3

from sys import stdin, argv
from string import ascii_letters, digits, punctuation
from hashlib import sha3_512 as shasum

MASTER_PASSWORD = **************************************************************
allowed_characters = list(sorted(set(digits + ascii_letters + "@.")))


def get_password(entropy):
    num = int(shasum((entropy + MASTER_PASSWORD).encode()).hexdigest(), 16)
    result = []
    while num:
        num, i = divmod(num, len(allowed_characters))
        result.append(allowed_characters[i])
    return "".join(result)


assert len(argv) > 1
print(get_password("".join(argv[1:])))
