#!/bin/sh
for rep in *; do
	cd "./$rep" 2> /dev/null || continue
	updated=$(git status | head -n2)
	[[ "$updated" == *"up to date"* ]] && test -z "$(git status -s)" &&
		cd .. && continue
	[[ "$updated" == *"up to date"* ]] &&
		printf "%8s%-50s\n" " " "$rep" | tr " " "-" ||
		printf "[LOCAL] %-50s\n" "$rep" | tr " " "-"
	git status -s
	cd ..
done
