#!/bin/sh
USERNAME=hvod2000
curl "https://api.github.com/users/$USERNAME/repos?per_page=999" |
jq ".[] | .name" -r | while read name; do
	[[ "$name" == gitbomb ]] && continue
	git clone "git@github.com:$USERNAME/$name.git" &
done
