#!/bin/python3

from ast import literal_eval
from pathlib import Path
from sys import argv, stdin


def list2hex(lst):
    return "".join(hex(numb)[2:].zfill(2) for numb in lst)


lst = literal_eval(Path(argv[1]).read_text())
if not isinstance(lst[0], list):
    target = '"' + list2hex(lst) + '"'
else:
    content = "\n".join("    " + list2hex(lst) for lst in lst)
    target = "[[int(r[i:i+2], 16) for i in range(0, len(r), 2)] for r in ("
    target += '\n"""\n' + content + '\n""".strip().split())]\n'
Path(argv[-1]).write_text(target)
