#!/bin/python3

from sys import stdin, argv

source = stdin
limit = 80
file = source
lines = iter(file.readlines())
indents, source = [], []
try:
    while True:
        line = next(lines)
        indents.append(len(line) - len(line.lstrip(" ")))
        source.append(line.strip())
except StopIteration:
    pass
source = " ".join(source)
sentences, i, j = [], 0, 0
while j < len(source):
    c = source[j]
    if c in ".!?:;":
        k = j
        while k < len(source) and source[k] in ".!?":
            k += 1
        sentences.append((source[i:j], source[j:k]))
        i = j = k + 1
        continue
    j += 1
if j - 1 > i:
    sentences.append((source[i:j], ""))
sentences = list(map(lambda x: (x[0].strip() + x[1]).split(), sentences))
def iter_indents(indents):
    yield from indents
    while True:
        yield indents[-1]
target = []
for indent in iter_indents(indents):
    if not sentences:
        break
    target.append(" " * indent + sentences[0].pop(0))
    while sentences:
        if not sentences[0]:
            sentences.pop(0)
            if len(target[-1]) * 3 > limit * 2 and (
                len(sentences) < 2
                or len(target[-1])
                + sum(map(lambda x: len(x), sentences[1]))
                + len(sentences[1]) > limit
            ):
                break
        elif len(sentences[0][0]) + len(target[-1]) < limit:
            target[-1] += " " + sentences[0].pop(0)
        else:
            break
print("\n".join(target))
