#!/bin/sh -e

app=$(xdotool getactivewindow getwindowname | sed -e "s@/@╱@g")
date=$(date +"%y%m%d")
time=$(date +"%T")
path=~/Pictures/Screenshots/"$date $time $app.png"
printf " ????  %s " "$path"
mkdir -p "$(dirname "$path")"
imlib2_grab "$path"
printf "\r[ OK ] %s\n" "$path"
xclip -selection clipboard -target image/png -i "$path"
