#!/bin/sh -e


while true; do
	sleep $((240 - $(date +%s) % 240))
	app=$(xdotool getactivewindow getwindowname | sed -e "s@/@╱@g")
	date=$(date +"%Y-%m-%d")
	time=$(date +"%H:%M")
	path=~/Pictures/Screenshots/"What I was doing that day?/$date/$time $app.png"
	echo "Saving $path..."
	mkdir -p "$(dirname "$path")"
	imlib2_grab "$path"
	echo "[ OK ] $path"
done
