#!/usr/bin/env python3

from pathlib import Path
from sys import argv


def utf_to_ascii(text):
    result = []
    for char in text:
        if ord(char) >= 128:
            result.append(f"U{ord(char)}")
        else:
            result.append(char)
    return "".join(result)


def handle(path):
    path = Path(path)
    if path.is_file():
        try:
            text = path.read_text()
            path.write_text(utf_to_ascii(text))
        except UnicodeDecodeError:
            print(f"{path} is not a plain text file.")
    else:
        for path in path.iterdir():
            utf_to_ascii(path)


for path in argv[1:]:
    handle(path)
