#!/bin/python3

from sys import stdin, argv
import codecs

SEPARATORS = ".!?:;"
f, limit = codecs.getreader("utf_8_sig")(stdin.buffer, errors="replace"), 80
if len(argv) > 1:
    limit = int(argv[1])
if len(argv) > 2:
    f = open(argv[2], mode="r", encoding="utf_8_sig")
lines = iter(f.readlines())
indents, source = [], []
try:
    while True:
        line = next(lines)
        indents.append(len(line) - len(line.lstrip(" ")))
        source.append(line.strip())
except StopIteration:
    pass
source = sum(map(lambda x: x.split(), source), [])
sentences = [[]]
for word in source:
    sentences[-1].append(word)
    if word[-1] in SEPARATORS:
        sentences.append([])
if not sentences[-1]:
    sentences.pop(-1)


def iter_indents(indents):
    yield from indents
    while True:
        yield indents[-1]


target = []
for indent in iter_indents(indents):
    if not sentences:
        break
    target.append(" " * indent + sentences[0].pop(0))
    while sentences:
        if not sentences[0]:
            sentences.pop(0)
            if len(target[-1]) * 3 > limit * 2 and (
                len(sentences) < 2
                or len(target[-1])
                + sum(map(lambda x: len(x), sentences[1]))
                + len(sentences[1])
                > limit
            ):
                break
        elif len(sentences[0][0]) + len(target[-1]) < limit:
            target[-1] += " " + sentences[0].pop(0)
        else:
            break
print("\n".join(target))
