#!/usr/bin/env python3

from random import choice, randint
from string import ascii_letters, digits, punctuation
from sys import argv, stdin


def random_word(length):
    chars = ascii_letters + digits + punctuation
    return "".join(choice(chars) for _ in range(length))


def random_sentence(words, word_min, word_max):
    words = [random_word(randint(word_min, word_max)) for _ in range(words)]
    return " ".join(words)


args = list(map(int, argv[1:]))
if len(args) == 0:
    print(random_sentence(1, 64, 64))
elif len(args) == 1:
    print(random_sentence(1, args[0], args[0]))
elif len(args) == 2:
    print(random_sentence(args[0], args[1], args[1]))
elif len(args) == 3:
    print(random_sentence(*args))
