#!/usr/bin/env python3

from sys import stderr

SUPERSCRIPT = {"+": "⁺", "-": "⁻", "=": "⁼", "(": "⁽", ")": "⁾"}
for i, char in enumerate("⁰¹²³⁴⁵⁶⁷⁸⁹"):
    SUPERSCRIPT[str(i)] = char


def superscript(text: str) -> str:
    result, bad_chars = [], set()
    for char in text:
        if char not in SUPERSCRIPT:
            if char not in bad_chars:
                print(f"superscripting {char!r} is not supported", file=stderr)
                bad_chars.add(char)
            continue
        result.append(SUPERSCRIPT[char])
    return "".join(result)


print(superscript(open(0).read()))
