#!/usr/bin/env python3

from pathlib import Path
from sys import argv, stdin


def replace_first(line, old, new):
    prefix = []
    while line.startswith(old):
        prefix.append(new)
        line = line.replace(old, "", 1)
    return "".join(prefix) + line


def indent_lines(lines, tab_size):
    return [replace_first(l, "\t", " " * tab_size) for l in lines]


def indent_file(path, tab_size):
    path = Path(path)
    if path.is_file():
        try:
            text = path.read_text().split("\n")
            path.write_text("\n".join(indent_lines(text, tab_size)))
        except UnicodeDecodeError as e:
            print(f"{path} is not a plain text file.")
    else:
        for path in path.iterdir():
            indent_file_with_tabs(path)


tab_size = 8
for arg in argv[1:]:
    if arg.startswith("tab_size="):
        tab_size = int(arg.removeprefix("tab_size="))
    else:
        indent_file(arg, tab_size)
