#!/usr/bin/env python3

from pathlib import Path
from sys import argv


def rstrip(path):
    path = Path(path)
    if path.is_file():
        try:
            text = path.read_text().split("\n")
            path.write_text("\n".join(line.rstrip() for line in text))
        except UnicodeDecodeError:
            print(f"{path} is not a plain text file.")
    else:
        for path in path.iterdir():
            rstrip(path)


for path in argv[1:]:
    rstrip(path)
