#!/bin/sh -e

if setxkbmap -query | grep variant > /dev/null; then
	setxkbmap us,ru
	notify-send -t 1000 "Layout" "QWERTY / ЙЦУКЕН"
else
	setxkbmap us,ru 3l,
	notify-send -t 1000 "Layout" "3L / ЙЦУКЕН"
fi
