#!/bin/sh -e

path=$1
[ -z "$path" ] && path=$(openssl rand -hex 32)
url="https://hvox.stream/$path/"
printf "Copying current directory to %s\n" "$url"
printf "%s" "$url" | xclip -selection clipboard
scp -pr "$(pwd)/"* "vps:/var/www/hvox.stream/public/tmp/$path/"
printf "%s\n" "This directory is now available at $url"
